# Generated by Django 3.0.5 on 2020-04-02 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_of_seats', models.IntegerField()),
                ('no_of_screens', models.IntegerField(default=1)),
                ('opening_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cinema',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('released_date', models.DateField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convoapis.Cinema')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('ticket_left', models.IntegerField()),
                ('ticket_cost', models.FloatField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convoapis.Cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convoapis.Movie')),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MaxLengthValidator(14), django.core.validators.MinLengthValidator(10), django.core.validators.validate_integer])),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('wallet', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'userprofile',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=255)),
                ('sold_at', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convoapis.Shows')),
                ('ticket_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convoapis.UserProfile')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
