# Generated by Django 3.0.5 on 2020-04-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapis', '0002_remove_movie_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.TextField(),
        ),
    ]
