# Generated by Django 3.0.5 on 2020-04-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapis', '0003_auto_20200403_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
