# Generated by Django 3.0.5 on 2020-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapis', '0004_auto_20200403_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=25),
        ),
    ]
