# Generated by Django 3.0.5 on 2020-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapis', '0006_auto_20200403_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sold_at',
            field=models.FloatField(),
        ),
    ]
